//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portol.Common {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Portol.Common.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        public static string AllFieldsRequired {
            get {
                return ResourceManager.GetString("AllFieldsRequired", resourceCulture);
            }
        }
        
        public static string Australia {
            get {
                return ResourceManager.GetString("Australia", resourceCulture);
            }
        }
        
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        public static string CodeNumberRequired {
            get {
                return ResourceManager.GetString("CodeNumberRequired", resourceCulture);
            }
        }
        
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        public static string DOBRequired {
            get {
                return ResourceManager.GetString("DOBRequired", resourceCulture);
            }
        }
        
        public static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        public static string EmailInUsedParameter {
            get {
                return ResourceManager.GetString("EmailInUsedParameter", resourceCulture);
            }
        }
        
        public static string EmailPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("EmailPasswordIsIncorrect", resourceCulture);
            }
        }
        
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        public static string IncorrectdateFormat {
            get {
                return ResourceManager.GetString("IncorrectdateFormat", resourceCulture);
            }
        }
        
        public static string IncorrectEmailformat {
            get {
                return ResourceManager.GetString("IncorrectEmailformat", resourceCulture);
            }
        }
        
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string LoginPortolLabel {
            get {
                return ResourceManager.GetString("LoginPortolLabel", resourceCulture);
            }
        }
        
        public static string MobileInUse {
            get {
                return ResourceManager.GetString("MobileInUse", resourceCulture);
            }
        }
        
        public static string MobileNumberEmailRequiered {
            get {
                return ResourceManager.GetString("MobileNumberEmailRequiered", resourceCulture);
            }
        }
        
        public static string NetworkConnectionError {
            get {
                return ResourceManager.GetString("NetworkConnectionError", resourceCulture);
            }
        }
        
        public static string NewPasswordsRequired {
            get {
                return ResourceManager.GetString("NewPasswordsRequired", resourceCulture);
            }
        }
        
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        public static string NewZealand {
            get {
                return ResourceManager.GetString("NewZealand", resourceCulture);
            }
        }
        
        public static string NotMatchEmails {
            get {
                return ResourceManager.GetString("NotMatchEmails", resourceCulture);
            }
        }
        
        public static string NotMatchPasswords {
            get {
                return ResourceManager.GetString("NotMatchPasswords", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        public static string PasswordEmailRequired {
            get {
                return ResourceManager.GetString("PasswordEmailRequired", resourceCulture);
            }
        }
        
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        public static string PasswordsNotEquals {
            get {
                return ResourceManager.GetString("PasswordsNotEquals", resourceCulture);
            }
        }
        
        public static string PasswordWhiteSpace {
            get {
                return ResourceManager.GetString("PasswordWhiteSpace", resourceCulture);
            }
        }
        
        public static string PhoneNotExist {
            get {
                return ResourceManager.GetString("PhoneNotExist", resourceCulture);
            }
        }
        
        public static string RecoveringPassword {
            get {
                return ResourceManager.GetString("RecoveringPassword", resourceCulture);
            }
        }
        
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        public static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        public static string StreetRequired {
            get {
                return ResourceManager.GetString("StreetRequired", resourceCulture);
            }
        }
        
        public static string SuburbRequired {
            get {
                return ResourceManager.GetString("SuburbRequired", resourceCulture);
            }
        }
        
        public static string UnitedKingdom {
            get {
                return ResourceManager.GetString("UnitedKingdom", resourceCulture);
            }
        }
        
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        public static string WrongCode {
            get {
                return ResourceManager.GetString("WrongCode", resourceCulture);
            }
        }
        
        public static string PostCodeRequired {
            get {
                return ResourceManager.GetString("PostCodeRequired", resourceCulture);
            }
        }
        
        public static string SelectAddress {
            get {
                return ResourceManager.GetString("SelectAddress", resourceCulture);
            }
        }
        
        public static string UserSuggestedAddress {
            get {
                return ResourceManager.GetString("UserSuggestedAddress", resourceCulture);
            }
        }
        
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string ContinueGuess {
            get {
                return ResourceManager.GetString("ContinueGuess", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Guess {
            get {
                return ResourceManager.GetString("Guess", resourceCulture);
            }
        }
        
        public static string GuessEmail {
            get {
                return ResourceManager.GetString("GuessEmail", resourceCulture);
            }
        }
        
        public static string LoginAgain {
            get {
                return ResourceManager.GetString("LoginAgain", resourceCulture);
            }
        }
        
        public static string MissingInformation {
            get {
                return ResourceManager.GetString("MissingInformation", resourceCulture);
            }
        }
        
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string NoMobileNumberEmail {
            get {
                return ResourceManager.GetString("NoMobileNumberEmail", resourceCulture);
            }
        }
        
        public static string PersonNoRegistered {
            get {
                return ResourceManager.GetString("PersonNoRegistered", resourceCulture);
            }
        }
        
        public static string ReceiverInformation {
            get {
                return ResourceManager.GetString("ReceiverInformation", resourceCulture);
            }
        }
        
        public static string ReceiverName {
            get {
                return ResourceManager.GetString("ReceiverName", resourceCulture);
            }
        }
        
        public static string ReceiverNameRequired {
            get {
                return ResourceManager.GetString("ReceiverNameRequired", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string MobileNumberRequiered {
            get {
                return ResourceManager.GetString("MobileNumberRequiered", resourceCulture);
            }
        }
        
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        public static string DropoffAddressRequired {
            get {
                return ResourceManager.GetString("DropoffAddressRequired", resourceCulture);
            }
        }
        
        public static string PickupAddressRequired {
            get {
                return ResourceManager.GetString("PickupAddressRequired", resourceCulture);
            }
        }
        
        public static string NoAvailableCamera {
            get {
                return ResourceManager.GetString("NoAvailableCamera", resourceCulture);
            }
        }
        
        public static string NoPickPhotoSupported {
            get {
                return ResourceManager.GetString("NoPickPhotoSupported", resourceCulture);
            }
        }
        
        public static string NoPickVideoSupported {
            get {
                return ResourceManager.GetString("NoPickVideoSupported", resourceCulture);
            }
        }
        
        public static string NoTakeVideoSupported {
            get {
                return ResourceManager.GetString("NoTakeVideoSupported", resourceCulture);
            }
        }
        
        public static string M3 {
            get {
                return ResourceManager.GetString("M3", resourceCulture);
            }
        }
        
        public static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        public static string WhereSendingTo {
            get {
                return ResourceManager.GetString("WhereSendingTo", resourceCulture);
            }
        }
        
        public static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        public static string MeasurementsRequired {
            get {
                return ResourceManager.GetString("MeasurementsRequired", resourceCulture);
            }
        }
        
        public static string PictureParcelRequired {
            get {
                return ResourceManager.GetString("PictureParcelRequired", resourceCulture);
            }
        }
        
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        public static string NexToDestination {
            get {
                return ResourceManager.GetString("NexToDestination", resourceCulture);
            }
        }
        
        public static string NoVehiculeTypeForParcel {
            get {
                return ResourceManager.GetString("NoVehiculeTypeForParcel", resourceCulture);
            }
        }
        
        public static string VehiculeTypeNoAvailable {
            get {
                return ResourceManager.GetString("VehiculeTypeNoAvailable", resourceCulture);
            }
        }
        
        public static string CostNotEstimatedTryAgain {
            get {
                return ResourceManager.GetString("CostNotEstimatedTryAgain", resourceCulture);
            }
        }
        
        public static string ProblemTryAgain {
            get {
                return ResourceManager.GetString("ProblemTryAgain", resourceCulture);
            }
        }
        
        public static string CreditCardNumberRequired {
            get {
                return ResourceManager.GetString("CreditCardNumberRequired", resourceCulture);
            }
        }
        
        public static string ExpiryMonthRequired {
            get {
                return ResourceManager.GetString("ExpiryMonthRequired", resourceCulture);
            }
        }
        
        public static string ExpiryYearRequired {
            get {
                return ResourceManager.GetString("ExpiryYearRequired", resourceCulture);
            }
        }
        
        public static string CustomerDetailsRequired {
            get {
                return ResourceManager.GetString("CustomerDetailsRequired", resourceCulture);
            }
        }
        
        public static string NoDeliveryInfo {
            get {
                return ResourceManager.GetString("NoDeliveryInfo", resourceCulture);
            }
        }
        
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        public static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
    }
}
