//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortolMobile.Forms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortolMobile.Forms.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account was created.
        /// </summary>
        internal static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required.
        /// </summary>
        internal static string AllFieldsRequired {
            get {
                return ResourceManager.GetString("AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string Australia {
            get {
                return ResourceManager.GetString("Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        internal static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Number Required.
        /// </summary>
        internal static string CodeNumberRequired {
            get {
                return ResourceManager.GetString("CodeNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        internal static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        internal static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.O.B.
        /// </summary>
        internal static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB Required.
        /// </summary>
        internal static string DOBRequired {
            get {
                return ResourceManager.GetString("DOBRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop off Address.
        /// </summary>
        internal static string DropoffAddress {
            get {
                return ResourceManager.GetString("DropoffAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email is already in use.
        /// </summary>
        internal static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email {0} is already being used.
        /// </summary>
        internal static string EmailInUsedParameter {
            get {
                return ResourceManager.GetString("EmailInUsedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Mobile Number.
        /// </summary>
        internal static string EmailMobileNumber {
            get {
                return ResourceManager.GetString("EmailMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and Password.
        /// </summary>
        internal static string EmailPassword {
            get {
                return ResourceManager.GetString("EmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password is incorrect.
        /// </summary>
        internal static string EmailPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("EmailPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your mobile number.
        /// </summary>
        internal static string EnterMobileNumber {
            get {
                return ResourceManager.GetString("EnterMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        internal static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the package details..
        /// </summary>
        internal static string EnterPackageDetails {
            get {
                return ResourceManager.GetString("EnterPackageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName Required.
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, there was an error, we are working on it, Thanks.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect date format.
        /// </summary>
        internal static string IncorrectdateFormat {
            get {
                return ResourceManager.GetString("IncorrectdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Email format.
        /// </summary>
        internal static string IncorrectEmailformat {
            get {
                return ResourceManager.GetString("IncorrectEmailformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the 4-digit code sent to you at.
        /// </summary>
        internal static string InsertCode {
            get {
                return ResourceManager.GetString("InsertCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName Required.
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s create a Portol.
        /// </summary>
        internal static string letsCreateAPortol {
            get {
                return ResourceManager.GetString("letsCreateAPortol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started with Portol.
        /// </summary>
        internal static string LoginPortolLabel {
            get {
                return ResourceManager.GetString("LoginPortolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile number is already in use.
        /// </summary>
        internal static string MobileInUse {
            get {
                return ResourceManager.GetString("MobileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile number is required.
        /// </summary>
        internal static string MobileNumberRequiered {
            get {
                return ResourceManager.GetString("MobileNumberRequiered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, looks like there is no internet connection.
        /// </summary>
        internal static string NetworkConnectionError {
            get {
                return ResourceManager.GetString("NetworkConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string NewPasswordConfirmation {
            get {
                return ResourceManager.GetString("NewPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm password are required.
        /// </summary>
        internal static string NewPasswordsRequired {
            get {
                return ResourceManager.GetString("NewPasswordsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand.
        /// </summary>
        internal static string NewZealand {
            get {
                return ResourceManager.GetString("NewZealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and confirm email don&apos;t match.
        /// </summary>
        internal static string NotMatchEmails {
            get {
                return ResourceManager.GetString("NotMatchEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm Password don&apos;t match.
        /// </summary>
        internal static string NotMatchPasswords {
            get {
                return ResourceManager.GetString("NotMatchPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed.
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email and Password are required.
        /// </summary>
        internal static string PasswordEmailRequired {
            get {
                return ResourceManager.GetString("PasswordEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords are not the same.
        /// </summary>
        internal static string PasswordsNotEquals {
            get {
                return ResourceManager.GetString("PasswordsNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty or whitespace only string..
        /// </summary>
        internal static string PasswordWhiteSpace {
            get {
                return ResourceManager.GetString("PasswordWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Details.
        /// </summary>
        internal static string PersonalDetails {
            get {
                return ResourceManager.GetString("PersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Address.
        /// </summary>
        internal static string PickupAddress {
            get {
                return ResourceManager.GetString("PickupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        internal static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Name.
        /// </summary>
        internal static string ReceiverName {
            get {
                return ResourceManager.GetString("ReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovering Password.
        /// </summary>
        internal static string RecoveringPassword {
            get {
                return ResourceManager.GetString("RecoveringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-send code.
        /// </summary>
        internal static string ReSendCode {
            get {
                return ResourceManager.GetString("ReSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required.
        /// </summary>
        internal static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street is required.
        /// </summary>
        internal static string StreetRequired {
            get {
                return ResourceManager.GetString("StreetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suburb.
        /// </summary>
        internal static string Suburb {
            get {
                return ResourceManager.GetString("Suburb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suburb is required.
        /// </summary>
        internal static string SuburbRequired {
            get {
                return ResourceManager.GetString("SuburbRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string UnitedKingdom {
            get {
                return ResourceManager.GetString("UnitedKingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit No.
        /// </summary>
        internal static string UnitNo {
            get {
                return ResourceManager.GetString("UnitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Does not Exist.
        /// </summary>
        internal static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumen.
        /// </summary>
        internal static string Volumen {
            get {
                return ResourceManager.GetString("Volumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will recive a code number within 5 minutes.
        /// </summary>
        internal static string WaitForCode {
            get {
                return ResourceManager.GetString("WaitForCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are we sending today?.
        /// </summary>
        internal static string WhatAreSending {
            get {
                return ResourceManager.GetString("WhatAreSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worth$$.
        /// </summary>
        internal static string Worth {
            get {
                return ResourceManager.GetString("Worth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Code you entered is incorrect.
        /// </summary>
        internal static string WrongCode {
            get {
                return ResourceManager.GetString("WrongCode", resourceCulture);
            }
        }
    }
}
